/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ReceptenRouteImport } from './routes/recepten'
import { Route as DagboekRouteImport } from './routes/dagboek'
import { Route as IndexRouteImport } from './routes/index'

const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptenRoute = ReceptenRouteImport.update({
  id: '/recepten',
  path: '/recepten',
  getParentRoute: () => rootRouteImport,
} as any)
const DagboekRoute = DagboekRouteImport.update({
  id: '/dagboek',
  path: '/dagboek',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dagboek': typeof DagboekRoute
  '/recepten': typeof ReceptenRoute
  '/scanner': typeof ScannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dagboek': typeof DagboekRoute
  '/recepten': typeof ReceptenRoute
  '/scanner': typeof ScannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dagboek': typeof DagboekRoute
  '/recepten': typeof ReceptenRoute
  '/scanner': typeof ScannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dagboek' | '/recepten' | '/scanner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dagboek' | '/recepten' | '/scanner'
  id: '__root__' | '/' | '/dagboek' | '/recepten' | '/scanner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DagboekRoute: typeof DagboekRoute
  ReceptenRoute: typeof ReceptenRoute
  ScannerRoute: typeof ScannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepten': {
      id: '/recepten'
      path: '/recepten'
      fullPath: '/recepten'
      preLoaderRoute: typeof ReceptenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dagboek': {
      id: '/dagboek'
      path: '/dagboek'
      fullPath: '/dagboek'
      preLoaderRoute: typeof DagboekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DagboekRoute: DagboekRoute,
  ReceptenRoute: ReceptenRoute,
  ScannerRoute: ScannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
